// DO NOT EDIT !!!
// THE FILE IS AUTO GENERATED BY github.com/fogfish/cloudmcp
// 2025-10-27 18:38:04.544025 +0200 EET m=+0.841218792
package main

import (
	"net/http"

  "github.com/aws/aws-lambda-go/lambda"
	"github.com/fogfish/cloudmcp/internal/gateway"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/fogfish/cloudmcp/examples/helloworld/server"
)

func main() {
	server, err := server.HelloWorld()
	if err != nil {
		panic(err)
	}

	handler := mcp.NewStreamableHTTPHandler(func(*http.Request) *mcp.Server {
		return server
	}, &mcp.StreamableHTTPOptions{
		Stateless:    true,
		JSONResponse: true,
	})

	srv := gateway.New(handler)

	lambda.Start(srv.Serve)
}
