// DO NOT EDIT !!!
// THE FILE IS AUTO GENERATED BY github.com/fogfish/cloudmcp
// 2025-10-27 19:04:36.736371 +0200 EET m=+1.380776501
package main

import (
	"net/http"

  "github.com/aws/aws-lambda-go/lambda"
	"github.com/fogfish/cloudmcp/internal/gateway"
	"github.com/modelcontextprotocol/go-sdk/mcp"
	"github.com/fogfish/cloudmcp/examples/serverless/sayer"
)

func main() {
	server := mcp.NewServer(
		&mcp.Implementation{Name: "Sayer", Version: "v0.0.0"},
		nil,
	)
	mcp.AddTool(server, &mcp.Tool{Name: "Sayer", Description: "says hi"}, sayer.Sayer)

	handler := mcp.NewStreamableHTTPHandler(func(*http.Request) *mcp.Server {
		return server
	}, &mcp.StreamableHTTPOptions{
		Stateless:    true,
		JSONResponse: true,
	})

	srv := gateway.New(handler)

	lambda.Start(srv.Serve)
}
